:construction_worker:  Create release with GitHub actions
bohning/usdb_syncer pull request #64
Opened 2022-12-26 12:32 UTC by g3n35i5

This resolves #27

2023-01-01 13:53 UTC, bohning commented on .github/workflows/release.yaml
>              APP_NAME: "USDB Syncer.app"
APP_NAME should be "USDB Syncer", right? The `.app` is appended as part of the `pyinstaller --windowed` process, I believe.

2023-01-29 11:49 UTC, RumovZ requested changes
Great job, works like a charm on Windows!

Do you know why Windows Defender would suddenly warn about running the app? It didn't with the previous exe.
It would also be convenient if we could skip the archiving on Windows and Linux. But not a big deal.

2023-01-29 11:49 UTC, RumovZ commented on .vscode/settings.json
> +  "editor.rulers": [120]
Was there any particular reason you changed this? It does'nt conform to our configured formatting rules.

2023-01-29 12:03 UTC, RumovZ approved these changes

2023-01-29 12:06 UTC, g3n35i5 commented
> Great job, works like a charm on Windows!
> 
> Do you know why Windows Defender would suddenly warn about running the app? It didn't with the previous exe. It would also be convenient if we could skip the archiving on Windows and Linux. But not a big deal.

I would leave this as a ZIP for two reasons: It saves storage space and unifies all platforms. Otherwise you always have to consider special conditions "If on Windows/Linux then don't zip, otherwise do".

On the subject of Windows Defender: I think that the warning should always come, because the exe is not signed?

2023-01-29 12:08 UTC, merged